"""`python -m bench.report table --results FILE [--target FILE] [--check]`

Renders a `bench/results/results.schema.json`-valid `results.json` into
the markdown results tables `bench/README.md` publishes, replacing the
content between two marker comments in `--target` (default
`bench/README.md`) and leaving everything else in the file untouched.
`--check` recomputes the tables and compares them against what
`--target` currently holds, exiting 1 on drift without writing anything:
"No number appears in any document in this repository that is not present
in a committed `results.json`, and no table is hand-edited"
(bench/README.md, "Results").

`render_block` and `splice` are the library functions this CLI wraps; a
test (or another script) can call them directly.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

START_MARKER = "<!-- bench-results:start -->"
END_MARKER = "<!-- bench-results:end -->"


def _fmt_metric(metric_value: dict[str, Any]) -> str:
    value = metric_value["value"]
    return "n/a" if value is None else f"{value:.3f}"


def render_entries_table(entries: list[dict[str, Any]]) -> str:
    if not entries:
        return "_No run set has been scored yet._"
    header = (
        "| Skill | Model | Domain | Artifact type | Artifacts | Recall | Precision | "
        "Clean FP rate | Consistency | Consistency (exact) | Unresolvable |\n"
        "|---|---|---|---|---|---|---|---|---|---|---|"
    )
    rows = [
        "| {skill} | {model} | {domain} | {artifact_type} | {n} | {recall} | {precision} | "
        "{fp} | {cons} | {cons_exact} | {unresolved} |".format(
            skill=e["skill"],
            model=e["model"],
            domain=e["domain"],
            artifact_type=e["artifact_type"],
            n=e["artifacts_scored"],
            recall=_fmt_metric(e["recall"]),
            precision=_fmt_metric(e["precision"]),
            fp=_fmt_metric(e["clean_fp_rate"]),
            cons=_fmt_metric(e["consistency"]),
            cons_exact=_fmt_metric(e["consistency_exact"]),
            unresolved=e["unresolvable_claims"],
        )
        for e in sorted(entries, key=lambda e: (e["domain"], e["skill"], e["model"]))
    ]
    return "\n".join([header, *rows])


def render_baseline_comparison(entries: list[dict[str, Any]]) -> str:
    """A skill-versus-baseline table, computed by matching `(domain,
    model)` pairs where one side carries `skill: "baseline-generic"`
    (bench/README.md, "Baseline comparison"). Nothing here is stored
    anywhere else: every figure already lives in `entries[]`, read once.
    """
    by_domain_model: dict[tuple[str, str], dict[str, dict[str, Any]]] = {}
    for e in entries:
        by_domain_model.setdefault((e["domain"], e["model"]), {})[e["skill"]] = e

    rows: list[str] = []
    for (domain, model), skills in sorted(by_domain_model.items()):
        baseline = skills.get("baseline-generic")
        if baseline is None:
            continue
        for skill_name in sorted(skills):
            if skill_name == "baseline-generic":
                continue
            entry = skills[skill_name]
            skill_recall = entry["recall"]["value"]
            baseline_recall = baseline["recall"]["value"]
            verdict = "n/a"
            if skill_recall is not None and baseline_recall is not None:
                if skill_recall > baseline_recall:
                    verdict = "beats baseline"
                elif skill_recall == baseline_recall:
                    verdict = "ties baseline"
                else:
                    verdict = "below baseline"
            rows.append(
                f"| {skill_name} | {domain} | {model} | {_fmt_metric(entry['recall'])} | "
                f"{_fmt_metric(baseline['recall'])} | {_fmt_metric(entry['precision'])} | "
                f"{_fmt_metric(baseline['precision'])} | {verdict} |"
            )

    if not rows:
        return "_No baseline comparison available yet._"
    header = (
        "| Skill | Domain | Model | Skill recall | Baseline recall | Skill precision | "
        "Baseline precision | Verdict |\n|---|---|---|---|---|---|---|---|"
    )
    return "\n".join([header, *rows])


def render_block(results: dict[str, Any]) -> str:
    """The full marker-to-marker text `--target` should hold for this
    `results.json`, markers included. An empty `entries[]` (no run set
    scored yet) renders a short placeholder rather than a "Run set
    `none`, generated 1970-01-01..." line built from filler values."""
    entries = results.get("entries", [])
    if not entries:
        return "\n".join(
            [
                START_MARKER,
                "<!-- Generated by `python -m bench.report table`. Do not edit by hand: run "
                "`python -m bench.metrics score` for a run set, then regenerate. -->",
                "",
                "_No run set has been scored yet._",
                END_MARKER,
            ]
        )
    return "\n".join(
        [
            START_MARKER,
            "<!-- Generated by `python -m bench.report table`. Do not edit by hand: edit "
            f"`bench/results/{results.get('run_set', '<run-set>')}/results.json` and regenerate. -->",
            "",
            f"Run set `{results.get('run_set', '?')}`, generated {results.get('generated_at', '?')}.",
            "",
            render_entries_table(entries),
            "",
            "**Baseline comparison.**",
            "",
            render_baseline_comparison(entries),
            END_MARKER,
        ]
    )


def splice(target_text: str, block: str) -> str:
    """Replace the marker-to-marker region of `target_text` with `block`
    (which itself starts and ends with the markers), leaving everything
    else untouched. Raises ValueError if the markers are not present."""
    if START_MARKER not in target_text or END_MARKER not in target_text:
        raise ValueError(
            f"{START_MARKER} / {END_MARKER} not found in target; add the pair once before "
            "this command can update it"
        )
    before = target_text.split(START_MARKER, 1)[0]
    after = target_text.split(END_MARKER, 1)[1]
    return before + block + after


def _build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="python -m bench.report", description="Render bench results.json into markdown result tables."
    )
    sub = parser.add_subparsers(dest="command", required=True)
    table_cmd = sub.add_parser("table", help="Render results.json into the markdown results tables.")
    table_cmd.add_argument("--results", required=True, type=Path, help="Path to a results.json")
    table_cmd.add_argument(
        "--target", type=Path, default=Path("bench/README.md"), help="Markdown file to update (default bench/README.md)"
    )
    table_cmd.add_argument(
        "--check", action="store_true", help="Compare against --target instead of writing; exit 1 on drift."
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = _build_arg_parser()
    args = parser.parse_args(argv)

    if args.command != "table":
        print(f"usage error: unknown command {args.command!r}", file=sys.stderr)
        return 1

    try:
        results = json.loads(args.results.read_text(encoding="utf-8"))
    except OSError as exc:
        print(f"usage error: cannot read {args.results}: {exc}", file=sys.stderr)
        return 1
    except json.JSONDecodeError as exc:
        print(f"usage error: {args.results} is not valid JSON: {exc}", file=sys.stderr)
        return 1

    if not args.target.exists():
        print(f"error: target file {args.target} does not exist", file=sys.stderr)
        return 1
    target_text = args.target.read_text(encoding="utf-8")

    block = render_block(results)
    try:
        new_text = splice(target_text, block)
    except ValueError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    if args.check:
        if new_text != target_text:
            print(f"drift: {args.target} does not match the table regenerated from {args.results}", file=sys.stderr)
            return 1
        print("no drift")
        return 0

    with args.target.open("w", encoding="utf-8", newline="\n") as handle:
        handle.write(new_text)
    print(f"updated {args.target}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
