"""Domain discovery. There is no discovery: this module holds one explicit
ordered tuple, per `bench/generator/README.md`, "Discovery". A domain that
is not listed here does not exist.

`bench/generator/README.md` shows the full six-launch-domain roster this
tuple grows to as each skill pipeline (S-05) contributes its own module.
Each stage appends its own module's dotted path here; it does not replace
this file wholesale.
"""

from __future__ import annotations

import importlib

from bench.generator.api import Domain

DOMAIN_MODULES: tuple[str, ...] = (
    "bench.generator.domains.toy",
    "bench.generator.domains.argument",
    "bench.generator.domains.docs",
    "bench.generator.domains.microcopy",
    "bench.generator.domains.usability",
    "bench.generator.domains.accessibility",
    "bench.generator.domains.clarity",
)


def load_domains(module_paths: tuple[str, ...] = DOMAIN_MODULES) -> tuple[Domain, ...]:
    """Import every listed domain module in order and return its `DOMAIN`.

    Import order does not affect any domain's generated bytes: each domain
    module registers into its own module-local `INJECTORS` dict (see
    `bench.generator.api.injector`), and every artifact seed derives from
    `(root_seed, domain_name, recipe_id)` alone. Order here only fixes CLI
    output order and, via `sorted(...)` at every call site that needs
    determinism, never anything written to a corpus file.
    """
    domains: list[Domain] = []
    seen_names: dict[str, str] = {}
    for module_path in module_paths:
        module = importlib.import_module(module_path)
        domain = getattr(module, "DOMAIN", None)
        if not isinstance(domain, Domain):
            raise TypeError(
                f"{module_path!r} does not export a module-level DOMAIN of type Domain"
            )
        if domain.name in seen_names:
            raise ValueError(
                f"domain name {domain.name!r} is registered twice: "
                f"{seen_names[domain.name]!r} and {module_path!r}"
            )
        seen_names[domain.name] = module_path
        domains.append(domain)
    return tuple(domains)
